[package]
edition = "2018"
build = "./common/build/build.rs"
name = "overlay"
version = "0.0.1"
description = "Overlay protocol library"

[dependencies]
arrayref = "0.3.5"
base64 = "0.11.0"
failure = "0.1.6"
hex = "^0"
lockfree = "0.5.1"
log = "0.4.8"
rand = "0.7.2"
sha2 = "0.8.0"
tokio = { version = "0.2.5", features = ["rt-threaded", "stream", "tcp", "udp"] }

adnl = { git = "https://github.com/tonlabs/ton-labs-adnl.git", features = ["node"] }
rldp = { git = "https://github.com/tonlabs/ton-labs-rldp.git" }
ton_api = { git = "https://github.com/tonlabs/ton-labs-tl.git", package = "ton_api" }
ton_block = { git = "https://github.com/tonlabs/ton-labs-block.git" }
ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }

[dev-dependencies]
dht = { git = "https://github.com/tonlabs/ton-labs-dht.git" }
ed25519-dalek = "1.0.0-pre.3"
log4rs = "0.8.3"
	
