[package]
build = './common/build/build.rs'
description = 'Overlay protocol library'
edition = '2018'
name = 'overlay'
resolver = '2'
version = '0.6.48'

[workspace]


[dependencies]
async-trait = '0.1'
base64 = '0.13'
failure = '0.1'
hex = '0.4'
log = '0.4'
rand = '0.7'
sha2 = '0.9'
adnl = { features = [ 'node' ], git = 'https://github.com/tonlabs/ton-labs-adnl', tag = '0.7.63' }
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
rldp = { git = 'https://github.com/tonlabs/ton-labs-rldp', tag = '0.7.59' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl', package = 'ton_api', tag = '0.2.116' }
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block', tag = '1.7.35' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types', tag = '1.10.12' }

[dev-dependencies]
external-ip = '4.1'
log4rs = '1.0'
serde_json = '1.0'
socket2 = '0.3'
dht = { git = 'https://github.com/tonlabs/ton-labs-dht', tag = '0.5.60' }

[features]
compression = [ 'adnl/compression' ]
telemetry = [ 'adnl/telemetry', 'rldp/telemetry' ]
telemetry_test_only = [ 'adnl/telemetry', 'dht/telemetry', 'rldp/telemetry' ]

